---
- name: Create a user
  hosts: all
  remote_user: root
  roles:
    - role: create-user

- name: Install conda
  hosts: all
  remote_user: "{{ inventory_hostname }}"
  roles:
    - role: magic-conda
