---
# tasks file for magic-conda

- name: Download conda Package
  get_url:
    url: {{ conda_source_url  }}
    dest: {{ conda_file_destination }}
    checksum: {{ conda_source_checksum}}
    mode: 0550

- name: Create conda install folder
  become: True
  file:
    path: {{ conda_install_path }}
    state: directory
    owner: {{ ansible_user }}
    mode: 755
    recurse: yes

- name: Install conda
  shell: {{ conda_file_destination }} -b -u -p {{ conda_install_path }}

- name: Remove the install file
  file:
    state: absent
    path: {{ conda_file_destination }}

- name: Add conda to path
  become: True
  shell: echo 'export PATH=$CONDA_PATH:$PATH' >> /etc/profile
  environment: 
    CONDA_PATH: {{ conda_install_path }}

- name: Set read permission for all
  become: True
  file:
    path: {{ conda_install_path + '/bin' }}
    mode: +r
    recurse: yes

- name: Set execution permission for all
  become: True
  file:
    path: {{ conda_install_path}}
