---
# tasks file for magic-conda

- name: Download conda Package
  get_url:
    url: "{{ conda_source_url  }}"
    dest: "{{ conda_file_destination }}"
    checksum: "{{ conda_source_checksum}}"
    mode: 0550

- name: Create conda install folder
  become: yes
  file:
    path: "{{ conda_install_path }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ ansible_user }}"

- name: Install conda
  shell: "{{ conda_file_destination }} -b -u -p {{ conda_install_path }}"

- name: Remove the install file
  become: yes
  file:
    state: absent
    path: "{{ conda_file_destination }}"

- name: Add conda to path
  become: yes
  shell: export PATH={{ conda_install_path + '/bin' }}:$PATH >> /etc/profile

- name: add cond path
  become: yes
  lineinfile:
    dest:           "/etc/environment"
    state:          present
    regexp:         "^(PATH=\")({{ conda_install_path + '/bin' }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ conda_install_path + '/bin' }}))))(:{{ conda_install_path + '/bin' }})?((?(4).*|\"))"
    line:           '\1\3:{{ conda_install_path }}/bin\5'
    backrefs:       yes


- name: Set read permission for all
  become: yes
  file:
    path: "{{ conda_install_path + '/bin' }}"
    mode: +r
    recurse: yes


- name: Set execution permission for all
  become: yes
  file:
    path: "{{ conda_install_path + '/bin' }}"


        
