---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest
    dockerfile: /home/user-ansible/test-ansible/roles/create_user/molecule/default/Dockerfile.j2
    pre_build_image: true
    priviledged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint:
  set -e
  yamllint .
  ansible-lint .